### ISSUE TITLE
TypeError: '<' not supported between instances of 'Mock' and 'int'

### ISSUE THREAD

**Issue by auramatics-tech** [bdragon300/pyzkaccess#11]
hello
I have a C3-400 device.

I can connect to the device, get the serial number and even open and close relays. 
I got TypeError: '<' not supported between instances of 'Mock' and 'int'

I have tried with the example code shared

![image](https://github.com/bdragon300/pyzkaccess/assets/98015329/38ba20ee-bb1e-4a9b-8048-598767dbd6b4)

**Comment by akhterarif** [comment]
I am also getting the same error. Is there anyone who can have a solution?

**Comment by bdragon300** [comment]
Hello.

Seems that you run the code on linux, but pyzkaccess is windows-only due to manufacturer's PULL SDK limitations. However on linux you may use Wine, it should work.
A new subcommand `pyzkaccess setup` introduced in v1.1 helps to check if the environment is correct.

Thanks.
