### ISSUE TITLE
Unable to enroll card with Numbers starting with 0

### ISSUE THREAD

**Issue by qzaman74** [bdragon300/pyzkaccess#3]
I've some cards whose numbers start with preceding 0 which is omitted when saving to controller.

**Comment by bdragon300** [comment]
Hello, sorry for long answer. I just can't check it right now, but card number doesn't get limited somehow. Looks like this is a limitation of PULL SDK which is used to communicate with devices.

**Comment by qzaman74** [comment]
Well I also found the same and then used to ommit preceding 0 from input to solve the problem.
