### ISSUE TITLE
"OSError: exception: access violation reading" on windows 2022

### ISSUE THREAD

**Issue by malikov-pro** [bdragon300/pyzkaccess#5]
plcommpro.dll ver 2.2.0.220, python 3.9 or 3.10 x64
OSError: exception: access violation reading

err = self.dll.GetDeviceParam(self.handle, buf, buffer_size, query)
similarly on C# (pull_sdk\Demo-C#\) and Go (https://github.com/bdragon300/gozkaccess)

on x32 error load library

**Comment by bdragon300** [comment]
Hello @malikov-pro . Sorry for late reply.
Have you tried to run your code on 32-bit python? Or maybe Windows UAC affects to library work somehow, try to disable it temporarily and check.

**Comment by SaadYasir** [comment]
I had same issue. try it with Python 32 bit version and it will work fine.
also copy the pull sdk dll files and put them in system32 and SysWow64 folders

**Comment by malikov-pro** [comment]
> I had same issue. try it with Python 32 bit version and it will work fine. also copy the pull sdk dll files and put them in system32 and SysWow64 folders

It works! Thank you
